# Generated by Django 6.0.6 on 2026-10-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_inquiry_testimony_project_created_at'),
    ]

    operations = [
    ]
